language: c
compiler:
- clang
- gcc
- gpp
- g++
script: cmake . && make && make test
matrix:
  include:
  -os: osx
    addons:
      homebrew:
        packages:
        - cmake
        update: true
  -os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
  -os: windows